name: Docker Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and Start Docker containers
      run: |
        docker-compose build
        docker-compose up -d
        
    - name: Check running containers
      run: docker-compose ps
      
    - name: Wait for Backend to be ready
      run: |
        echo "Waiting for backend to be ready..."
        timeout 60s bash -c 'until $(curl --output /dev/null --silent --head --fail http://localhost:3000/api); do printf "."; sleep 2; done'
        echo "Backend is up!"
        
    - name: Import seed data
      run: docker-compose exec -T backend npm run data:import
      
    - name: Run Backend Tests
      run: docker-compose exec -T backend npm test
      
    - name: Stop containers
      if: always()
      run: docker-compose down 